name: Code Check
on:  [ push ]

jobs:
  ruff-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Run Ruff
        run: ruff check --output-format=github .

  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Ruff Format Check
        run: ruff format --diff

  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: chartboost/ruff-action@v1
      - uses: yezz123/setup-uv@v4
      - run: |
          pwd
          ls -laR
          pwd
          which uv
          uv export > requirements.txt
      - uses: pypa/gh-action-pip-audit@v1.0.0
        with:
          inputs: requirements.txt
