name: Pip Audit
on: [ push ]

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: yezz123/setup-uv@v4
      - run: |
          uv export >> requirements.txt
          ls -la requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: pypa/gh-action-pip-audit@v1.0.0
        with:
          inputs: requirements.txt
