name: Code Check
on: [ push ]

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yezz123/setup-uv@v4
      - run: uv export > requirements.txt
      - uses: pypa/gh-action-pip-audit@v1.0.0
        with:
          inputs: requirements.txt
